# Create dataFrame

Clone the repo and run the following commands to start a venv and install the libraries needed

In [ ]:
#start a virtual enviroment
python3 -m venv .venv
source .venv/bin/activate

# Code explenation

This first snippet will create a dataframe from the csv object and will print the first 10 rows of the dataframes
beacuse of the google column that appears in the data set we neet to ignore the rows that makes the df object read everything as strings

In [52]:
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv('google_5yr_one.csv', na_values=['GOOGL', 'null', 'N/A'])

df.head(11)

          Date      Close       High        Low       Open      Volume
0          NaN        NaN        NaN        NaN        NaN         NaN
1   2020-06-04  70.378517  71.723094  69.965992  71.497169  26982000.0
2   2020-06-05  71.658401  71.970910  70.046107  70.445200  42642000.0
3   2020-06-08  72.057487  72.105256  70.885091  70.974667  33878000.0
4   2020-06-09  72.258530  73.040793  71.774842  71.918162  33624000.0
5   2020-06-10  72.886528  73.288104  72.371990  72.727787  31762000.0
6   2020-06-11  69.761475  72.234651  69.587805  71.708662  47144000.0
7   2020-06-12  70.309853  71.384214  68.960302  70.953770  36676000.0
8   2020-06-15  70.698990  70.910974  69.029968  69.143925  30468000.0
9   2020-06-16  71.979370  72.511821  71.109528  72.105264  30648000.0
10  2020-06-17  72.281425  72.762129  71.415069  72.301335  30610000.0

# simple type snippet

In [38]:
df.dtypes

Date       object
Close     float64
High      float64
Low       float64
Open      float64
Volume    float64
dtype: object

# print general statistics

In [ ]:
print(df.describe())

             Close         High          Low         Open        Volume
count  1255.000000  1255.000000  1255.000000  1255.000000  1.255000e+03
mean    127.343522   128.767640   125.894397   127.286213  3.211913e+07
std      31.589957    31.873115    31.332366    31.626389  1.354981e+07
min      67.802834    69.567407    67.260929    67.693363  9.312000e+06
25%     102.415359   103.588002   101.102139   102.211330  2.333280e+07
50%     128.465805   130.137811   126.953037   128.635000  2.882800e+07
75%     147.319427   148.956410   146.023874   147.533393  3.675800e+07
max     206.142593   206.811821   202.576693   203.156027  1.274901e+08

# Get data from a specifik conditon

In [ ]:
open_over_200 = df[df["Open"] > 200]
open_over_200

            Date       Close        High         Low        Open      Volume
1172  2025-01-31  203.785309  205.243621  201.567861  201.767628  32042000.0
1173  2025-02-03  200.998505  203.515610  199.869815  200.459133  27838300.0
1174  2025-02-04  206.142593  206.811821  202.576693  203.156027  43856400.0